import { MethodMapList } from "@/types";

const creditMap: MethodMapList = {
    GyBs: { sd: 'GyBs', momo: '' },
    GyOe: { sd: 'GyOe', momo: '' },
    GySum: { sd: 'GySum', momo: '' },
    OneBs: { sd: 'OneBs', momo: '' },
    OneOe: { sd: 'OneOe', momo: '' },
    OneLh: { sd: 'OneLh', momo: '' },
    OneNumber: { sd: 'OneNumber', momo: '' },
    TwoBs: { sd: 'TwoBs', momo: '' },
    TwoOe: { sd: 'TwoOe', momo: '' },
    TwoLh: { sd: 'TwoLh', momo: '' },
    TwoNumber: { sd: 'TwoNumber', momo: '' },
    ThreeBs: { sd: 'ThreeBs', momo: '' },
    ThreeOe: { sd: 'ThreeOe', momo: '' },
    ThreeLh: { sd: 'ThreeLh', momo: '' },
    ThreeNumber: { sd: 'ThreeNumber', momo: '' },
    FourBs: { sd: 'FourBs', momo: '' },
    FourOe: { sd: 'FourOe', momo: '' },
    FourLh: { sd: 'FourLh', momo: '' },
    FourNumber: { sd: 'FourNumber', momo: '' },
    FiveBs: { sd: 'FiveBs', momo: '' },
    FiveOe: { sd: 'FiveOe', momo: '' },
    FiveLh: { sd: 'FiveLh', momo: '' },
    FiveNumber: { sd: 'FiveNumber', momo: '' },
    SixBs: { sd: 'SixBs', momo: '' },
    SixOe: { sd: 'SixOe', momo: '' },
    SixLh: { sd: 'SixLh', momo: '' },
    SixNumber: { sd: 'SixNumber', momo: '' },
    SevenBs: { sd: 'SevenBs', momo: '' },
    SevenOe: { sd: 'SevenOe', momo: '' },
    SevenLh: { sd: 'SevenLh', momo: '' },
    SevenNumber: { sd: 'SevenNumber', momo: '' },
    EightBs: { sd: 'EightBs', momo: '' },
    EightOe: { sd: 'EightOe', momo: '' },
    EightLh: { sd: 'EightLh', momo: '' },
    EightNumber: { sd: 'EightNumber', momo: '' },
    NineBs: { sd: 'NineBs', momo: '' },
    NineOe: { sd: 'NineOe', momo: '' },
    NineLh: { sd: 'NineLh', momo: '' },
    NineNumber: { sd: 'NineNumber', momo: '' },
    TenBs: { sd: 'TenBs', momo: '' },
    TenOe: { sd: 'TenOe', momo: '' },
    TenLh: { sd: 'TenLh', momo: '' },
    TenNumber: { sd: 'TenNumber', momo: '' },
};

export default creditMap;