import { MethodMapList } from "@/types"

const officialMap: MethodMapList = {
    "WxZx": { sd: "WxZx", momo: "SSC_ZX5" },
    "WxZxDs": { sd: "WxZxDs", momo: "SSC_ZX5_S" },
    "WxZxZh": { sd: "WxZxZh", momo: "SSC_ZH5" },
    "WxZu120": { sd: "WxZu120", momo: "SSC_WXZU120" },
    "WxZu60": { sd: "WxZu60", momo: "SSC_WXZU60" },
    "WxZu30": { sd: "WxZu30", momo: "SSC_WXZU30" },
    "WxZu20": { sd: "WxZu20", momo: "SSC_WXZU20" },
    "WxZu10": { sd: "WxZu10", momo: "SSC_WXZU10" },
    "WxZu5": { sd: "WxZu5", momo: "SSC_WXZU5" },

    "QsiZx": { sd: "QsiZx", momo: "SSC_ZX4" },
    "QsiZxDs": { sd: "QsiZxDs", momo: "SSC_ZX4_S" },
    "QsiZxZh": { sd: "QsiZxZh", momo: "SSC_ZH4" },
    "QsiZu24": { sd: "QsiZu24", momo: "SSC_SXZU24" },
    "QsiZu12": { sd: "QsiZu12", momo: "SSC_SXZU12" },
    "QsiZu6": { sd: "QsiZu6", momo: "SSC_SXZU6" },
    "QsiZu4": { sd: "QsiZu4", momo: "SSC_SXZU4" },

    "HsiZx": { sd: "HsiZx", momo: "SSC_ZX4" },
    "HsiZxDs": { sd: "HsiZxDs", momo: "SSC_ZX4_S" },
    "HsiZxZh": { sd: "HsiZxZh", momo: "SSC_ZH4" },
    "HsiZu24": { sd: "HsiZu24", momo: "SSC_SXZU24" },
    "HsiZu12": { sd: "HsiZu12", momo: "SSC_SXZU12" },
    "HsiZu6": { sd: "HsiZu6", momo: "SSC_SXZU6" },
    "HsiZu4": { sd: "HsiZu4", momo: "SSC_SXZU4" },

    "QsZx": { sd: "QsZx", momo: "SSC_QZX3" },
    "QsZxDs": { sd: "QsZxDs", momo: "SSC_QZX3_S" },
    "QsZxHz": { sd: "QsZxHz", momo: "SSC_QZXHZ" },
    "QsZxKd": { sd: "QsZxKd", momo: "SSC_QZXKD" },
    "QsZxZh": { sd: "QsZxZh", momo: "SSC_QZH3" },
    "QsZu3": { sd: "QsZu3", momo: "SSC_QZUS" },
    "QsZu3Ds": { sd: "QsZu3Ds", momo: "SSC_QZUS_S" },
    "QsZu6": { sd: "QsZu6", momo: "SSC_QZUL" },
    "QsZu6Ds": { sd: "QsZu6Ds", momo: "SSC_QZUL_S" },
    "QsZuBd": { sd: "QsZuBd", momo: "SSC_QZUBD" },
    "QsZuHz": { sd: "QsZuHz", momo: "SSC_QZUHZ" },
    "QsHzWs": { sd: "QsHzWs", momo: "SSC_QHZWS" },

    "ZsZx": { sd: "ZsZx", momo: "SSC_ZZX3" },
    "ZsZxDs": { sd: "ZsZxDs", momo: "SSC_ZZX3_S" },
    "ZsZxHz": { sd: "ZsZxHz", momo: "SSC_ZZXHZ" },
    "ZsZxKd": { sd: "ZsZxKd", momo: "SSC_ZZXKD" },
    "ZsZxZh": { sd: "ZsZxZh", momo: "SSC_ZZH3" },
    "ZsZu3": { sd: "ZsZu3", momo: "SSC_ZZUS" },
    "ZsZu3Ds": { sd: "ZsZu3Ds", momo: "SSC_ZZUS_S" },
    "ZsZu6": { sd: "ZsZu6", momo: "SSC_ZZUL" },
    "ZsZu6Ds": { sd: "ZsZu6Ds", momo: "SSC_ZZUL_S" },
    "ZsZuBd": { sd: "ZsZuBd", momo: "SSC_ZZUBD" },
    "ZsZuHz": { sd: "ZsZuHz", momo: "SSC_ZZUHZ" },
    "ZsHzWs": { sd: "ZsHzWs", momo: "SSC_ZHZWS" },

    "HsZx": { sd: "HsZx", momo: "SSC_HZX3" },
    "HsZxDs": { sd: "HsZxDs", momo: "SSC_HZX3_S" },
    "HsZxHz": { sd: "HsZxHz", momo: "SSC_HZXHZ" },
    "HsZxKd": { sd: "HsZxKd", momo: "SSC_HZXKD" },
    "HsZxZh": { sd: "HsZxZh", momo: "SSC_HZH3" },
    "HsZu3": { sd: "HsZu3", momo: "SSC_HZUS" },
    "HsZu3Ds": { sd: "HsZu3Ds", momo: "SSC_HZUS_S" },
    "HsZu6": { sd: "HsZu6", momo: "SSC_HZUL" },
    "HsZu6Ds": { sd: "HsZu6Ds", momo: "SSC_HZUL_S" },
    "HsZuBd": { sd: "HsZuBd", momo: "SSC_HZUBD" },
    "HsZuHz": { sd: "HsZuHz", momo: "SSC_HZUHZ" },
    "HsHzWs": { sd: "HsHzWs", momo: "SSC_HHZWS" },

    "QeZx": { sd: "QeZx", momo: "SSC_QZX2" },
    "QeZxDs": { sd: "QeZxDs", momo: "SSC_QZX2_S" },
    "QeZxHz": { sd: "QeZxHz", momo: "SSC_QZXHZ2" },
    "QeZxKd": { sd: "QeZxKd", momo: "SSC_QZXKD2" },
    "QeZu": { sd: "QeZu", momo: "SSC_QZU2" },
    "QeZuBd": { sd: "QeZuBd", momo: "SSC_QZUBD2" },
    "QeZuDs": { sd: "QeZuDs", momo: "SSC_QZU2_S" },
    "QeZuHz": { sd: "QeZuHz", momo: "SSC_QZUHZ2" },

    "HeZx": { sd: "HeZx", momo: "SSC_HZX2" },
    "HeZxDs": { sd: "HeZxDs", momo: "SSC_HZX2_S" },
    "HeZxHz": { sd: "HeZxHz", momo: "SSC_HZXHZ2" },
    "HeZxKd": { sd: "HeZxKd", momo: "SSC_HZXKD2" },
    "HeZu": { sd: "HeZu", momo: "SSC_HZU2" },
    "HeZuBd": { sd: "HeZuBd", momo: "SSC_HZUBD2" },
    "HeZuDs": { sd: "HeZuDs", momo: "SSC_HZU2_S" },
    "HeZuHz": { sd: "HeZuHz", momo: "SSC_HZUHZ2" },

    "Dwd": { sd: "Dwd", momo: "SSC_DWD" },

    "BdwWuEm": { sd: "BdwWuEm", momo: "SSC_BDW52" },
    "BdwWuSm": { sd: "BdwWuSm", momo: "SSC_BDW53" },
    "BdwWuYm": { sd: "BdwWuYm", momo: "SSC_YFFS" },
    "BdwQsEm": { sd: "BdwQsEm", momo: "SSC_QBDW2" },
    "BdwQsYm": { sd: "BdwQsYm", momo: "SSC_QBDW1" },
    "BdwQsiEm": { sd: "BdwQsiEm", momo: "SSC_BDW42" },
    "BdwQsiSm": { sd: "BdwQsiSm", momo: "" },
    "BdwQsiYm": { sd: "BdwQsiYm", momo: "SSC_BDW41" },
    "BdwHsEm": { sd: "BdwHsEm", momo: "SSC_HBDW2" },
    "BdwHsYm": { sd: "BdwHsYm", momo: "SSC_HBDW1" },
    "BdwHsiEm": { sd: "BdwHsiEm", momo: "SSC_BDW42" },
    "BdwHsiSm": { sd: "BdwHsiSm", momo: "" },
    "BdwHsiYm": { sd: "BdwHsiYm", momo: "SSC_BDW41" },
    "BdwZsEm": { sd: "BdwZsEm", momo: "SSC_ZBDW2" },
    "BdwZsYm": { sd: "BdwZsYm", momo: "SSC_ZBDW1" },

    "BsoeQeZh": { sd: "BsoeQeZh", momo: "BsoeQeZh" },
    "BsoeQsZh": { sd: "BsoeQsZh", momo: "BsoeQeZh" },
    "BsoeHeZh": { sd: "BsoeHeZh", momo: "BsoeQeZh" },
    "BsoeHsZh": { sd: "BsoeHsZh", momo: "BsoeQeZh" },
    "BsoeWxHz": { sd: "BsoeWxHz", momo: "BsoeWxHz" },
    "BsoeQsHz": { sd: "BsoeQsHz", momo: "BsoeQsHz" },
    "BsoeZsHz": { sd: "BsoeZsHz", momo: "BsoeZsHz" },
    "BsoeHsHz": { sd: "BsoeHsHz", momo: "BsoeHsHz" },

    "QwHscs": { sd: "QwHscs", momo: "SSC_HSCS" },
    "QwSjfc": { sd: "QwSjfc", momo: "SSC_SJFC" },
    "QwSxbx": { sd: "QwSxbx", momo: "SSC_SXBX" },
    "QwYffs": { sd: "QwYffs", momo: "SSC_YFFS" },

    "ReZx": { sd: "ReZx", momo: "ReZx" },
    "ReZxDs": { sd: "ReZxDs", momo: "ReZxDs" },
    "ReZxHz": { sd: "ReZxHz", momo: "ReZxHz" },
    "ReZu": { sd: "ReZu", momo: "ReZu" },
    "ReZuDs": { sd: "ReZuDs", momo: "ReZuDs" },
    "ReZuHz": { sd: "ReZuHz", momo: "ReZuHz" },
    "ReZuBd": { sd: "ReZuBd", momo: "ReZuBd" },

    "RsZx": { sd: "RsZx", momo: "RsZx" },
    "RsZxDs": { sd: "RsZxDs", momo: "RsZxDs" },
    "RsZxHz": { sd: "RsZxHz", momo: "RsZxHz" },
    "RsZu": { sd: "RsZu", momo: "RsZu" },
    "RsZuDs": { sd: "RsZuDs", momo: "RsZuDs" },
    "RsZuHz": { sd: "RsZuHz", momo: "RsZuHz" },
    "RsZuBd": { sd: "RsZuBd", momo: "RsZuBd" },

    "RsiZx": { sd: "RsiZx", momo: "RsiZx" },
    "RsiZxDs": { sd: "RsiZxDs", momo: "RsiZxDs" },
    "RsiZxHz": { sd: "RsiZxHz", momo: "RsiZxHz" },
    "RsiZu": { sd: "RsiZu", momo: "RsiZu" },
    "RsiZuDs": { sd: "RsiZuDs", momo: "RsiZuDs" },
    "RsiZuHz": { sd: "RsiZuHz", momo: "RsiZuHz" },
    "RsiZuBd": { sd: "RsiZuBd", momo: "RsiZuBd" },

    "LhBg": { sd: "LhBg", momo: "SSC_RLH" },
    "LhBs": { sd: "LhBs", momo: "SSC_RLH" },
    "LhQb": { sd: "LhQb", momo: "SSC_RLH" },
    "LhQg": { sd: "LhQg", momo: "SSC_RLH" },
    "LhQs": { sd: "LhQs", momo: "SSC_RLH" },
    "LhSg": { sd: "LhSg", momo: "SSC_HLH" },
    "LhWb": { sd: "LhWb", momo: "SSC_RLH" },
    "LhWg": { sd: "LhWg", momo: "SSC_RLH" },
    "LhWq": { sd: "LhWq", momo: "SSC_QLH" },
    "LhWs": { sd: "LhWs", momo: "SSC_RLH" },

    "Sh": { sd: "Sh", momo: "SSC_Sh" },

    "ZjhQs": { sd: "ZjhQs", momo: "SSC_ZjhQs" },
    "ZjhZs": { sd: "ZjhZs", momo: "SSC_ZjhZs" },
    "ZjhHs": { sd: "ZjhHs", momo: "SSC_ZjhHs" },

    "Nn": { sd: "Nn", momo: "SSC_Nn" },
};

export default officialMap;